{
 "title": "Dashboard - APIs Products",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(http_requests_received_total, instance)"
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidade de requisições por endpoints - RegisterProductsService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "register_products_service{endpoint=\"/api/Products\",instance=\"docker.for.win.localhost:5000\",job=\"register-products-service-prometheus\",method=\"POST\"}",
     "legendFormat": "/api/Products"
    },
    {
     "expr": "register_products_service{endpoint=\"/api/Products\",instance=\"docker.for.win.localhost:5000\",job=\"register-products-service-prometheus\",method=\"GET\"}",
     "legendFormat": "/api/Products"
    }
   ]
  },
  {
   "title": "Register Products Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "register_products_service{endpoint=\"/api/Products\",instance=\"docker.for.win.localhost:5000\",job=\"register-products-service-prometheus\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Em Progresso (global)",
   "type": "singlestat",
   "description": "Em TODOS os controladores globalmente!",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m]))"
    }
   ]
  },
  {
   "title": "Taxa de requisições por segundos recebidas por controllers",
   "type": "graph",
   "description": "contabiliza todas as requisições, tanto com sucesso como com falhas.",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\",  code !~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\",  code !~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Duração das Requisições (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{instance =~ \"$instances\", controller =~ \"$controllers\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Taxa de requisições de erro por segundos por controller",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance=~\"$instances\", controller=~\"$controllers\", code=~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance=~\"$instances\",controller=\"\", code=~\"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}